# Generated by Django 5.1.1 on 2024-10-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_movie_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='img',
        ),
        migrations.AddField(
            model_name='movie',
            name='thumb',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
